# Generated by Django 2.0.7 on 2018-07-26 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20180726_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.DateField(default=datetime.date(2018, 7, 26)),
        ),
    ]
