# Generated by Django 2.0.7 on 2018-07-27 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20180726_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.DateField(default=datetime.date(2018, 7, 27)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.PositiveIntegerField(choices=[(None, '選択してください'), (30, '00:30'), (60, '01:00'), (90, '01:30'), (120, '02:00'), (150, '02:30'), (180, '03:00'), (210, '03:30'), (240, '04:00'), (270, '04:30'), (300, '05:00'), (330, '05:30'), (360, '06:00'), (390, '06:30'), (420, '07:00'), (450, '07:30'), (480, '08:00')]),
        ),
    ]
