# Generated by Django 2.0.7 on 2018-07-27 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0004_auto_20180727_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.PositiveIntegerField(choices=[(None, '選択'), (30, '00:30'), (60, '01:00'), (90, '01:30'), (120, '02:00'), (150, '02:30'), (180, '03:00'), (210, '03:30'), (240, '04:00'), (270, '04:30'), (300, '05:00'), (330, '05:30'), (360, '06:00'), (390, '06:30'), (420, '07:00'), (450, '07:30'), (480, '08:00')]),
        ),
    ]
