# Generated by Django 2.0.7 on 2018-07-29 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20180728_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.DateField(default=datetime.date(2018, 7, 29)),
        ),
    ]
